//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvhASPNETLesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvhKetQua
    {
        public string LvhMaSV { get; set; }
        public string LvhMaMH { get; set; }
        public Nullable<decimal> LvhDiem { get; set; }
    
        public virtual LvhMonHoc LvhMonHoc { get; set; }
        public virtual LvhSinhVien LvhSinhVien { get; set; }
    }
}
