//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvhASPNETLesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvhMonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LvhMonHoc()
        {
            this.LvhKetQuas = new HashSet<LvhKetQua>();
        }
    
        public string LvhMaMH { get; set; }
        public string LvhTenMH { get; set; }
        public Nullable<int> LvhSotiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LvhKetQua> LvhKetQuas { get; set; }
    }
}
