//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvhASPNETLesson10.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LvhK22CNT1Lesson09Entities : DbContext
    {
        public LvhK22CNT1Lesson09Entities()
            : base("name=LvhK22CNT1Lesson09Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LvhKetQua> LvhKetQuas { get; set; }
        public virtual DbSet<LvhKhoa> LvhKhoas { get; set; }
        public virtual DbSet<LvhMonHoc> LvhMonHocs { get; set; }
        public virtual DbSet<LvhSinhVien> LvhSinhViens { get; set; }
    }
}
