//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvhASPNETLesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvhSinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LvhSinhVien()
        {
            this.LvhKetQuas = new HashSet<LvhKetQua>();
        }
    
        public string LvhMaSV { get; set; }
        public string LvhHoSV { get; set; }
        public string LvhTenSV { get; set; }
        public Nullable<bool> LvhPhai { get; set; }
        public Nullable<System.DateTime> LvhNgaySinh { get; set; }
        public string LvhNoiSinh { get; set; }
        public string LvhMaKH { get; set; }
        public Nullable<decimal> LvhHocBong { get; set; }
        public Nullable<decimal> LvhDiemTrungBinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LvhKetQua> LvhKetQuas { get; set; }
        public virtual LvhKhoa LvhKhoa { get; set; }
    }
}
